/**
 * event constants
 */
export namespace EventConstants {

  export const RDB_MONITOR = 'rdb_monitor'

  export const DB_NAME = 'db_name'

  export const TABLE_NAME = 'table_name'

  export const SCENE_NAME = 'scene_name'

  export const ERROR_NAME = 'error_name'

  export const ERROR_MSG = 'error_msg'

  export const DURATION = 'duration'

  export const SQL = 'sql'

  /**
   * init
   */
  export const INIT_SCENE = 'init_scene'

  /**
   * query
   */
  export const QUERY_SCENE = 'query_scene'

  /**
   * error
   */
  export const ERROR_SCENE = 'error_scene'

  /**
   * table size
   */
  export const TABLE_SIZE_SCENE = 'table_size_scene'
}